server:
  port: 5005
  runMode: debug
logger:
  filePath: ../logs/logs.log
  encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: false
redis:
  host: localhost
  port: 6380
  password: password
  db: 0
  minIdleConnections: 100
  poolSize: 5000
  pollTimeout: 240
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
otp:
  expireTime: 120
  digits: 6
  limiter: 100
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 1440
  refreshTokenExpireDuration: 60
